import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppDrawer from "@/components/ui/AppDrawer/appDrawer";
import { AppUserAvatar } from "@/components/ui/appUserAvatar";
import AppSearch from "@/components/ui/appSearch";
import AppHome from "@/components/ui/appHome";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <AppDrawer>
          <div data-position="left" className="p-2 flex flex-col gap-2 justify-center items-center">
            <AppUserAvatar />
            <AppHome />
            <AppSearch />
          </div>
        </AppDrawer>
      </body>
    </html>
  );
}
