import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar, AppSidebarContentProvider, AppMobileHeader } from "@/components/ui/appSidebar";
import { AppRightPanelProvider } from "@/components/ui/appRightPanel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider defaultOpen={false}>
          <AppSidebarContentProvider>
            <AppSidebar />
            <SidebarInset>
              <AppMobileHeader />
              <AppRightPanelProvider>
                {children}
              </AppRightPanelProvider>
            </SidebarInset>
          </AppSidebarContentProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
