openapi: 3.0.3
info:
  title: Application Manager API (Baseline)
  version: 0.1.0
  description: >-
    Endpoints derived from baseline functional requirements. Shapes align with
    types in types.d.ts and specification in specs/001-baseline-spec/spec.md.
servers:
  - url: http://localhost:3000
paths:
  /api/jobs:
    get:
      summary: List jobs
      description: Returns an array of Job objects (see components.schemas.Job)
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number (>=1)
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Page size (1..100)
        - in: query
          name: sort
          schema:
            type: string
            enum: [postedAt, filteredAt]
          description: Sort field
        - in: query
          name: order
          schema:
            type: string
            enum: [asc, desc]
          description: Sort order
        - in: query
          name: filterResult
          schema:
            type: string
            enum: [true, false, error, undefined]
          description: Filter by relevance outcome
        - in: query
          name: filter
          schema:
            type: string
            enum: [relevant]
          description: Alias for filterResult=true
      responses:
        '200':
          description: OK
          headers:
            X-Total-Count:
              schema:
                type: integer
              description: Optional total count header
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      summary: Ingest jobs from configured source(s)
      description: Adds jobs with deduplication by (trackingId, refId)
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngestRequest'
      responses:
        '200':
          description: Ingestion summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngestSummary'
        '400':
          $ref: '#/components/responses/BadRequest'
        '429':
          $ref: '#/components/responses/RateLimited'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/jobs/{id}:
    get:
      summary: Get job by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/filter:
    post:
      summary: Run deterministic relevance filter on new jobs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilterRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilterAgentResult'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/RateLimited'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/jobs/{id}/generate:
    post:
      summary: Generate application documents for a job
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateRequest'
      responses:
        '202':
          description: Accepted (async)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateAcceptedResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/RateLimited'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/jobs/{id}/download:
    get:
      summary: Download generated documents
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: type
          required: true
          schema:
            $ref: '#/components/schemas/JobArtifactType'
          description: Artifact type to download
      responses:
        '200':
          description: OK
          headers:
            Content-Disposition:
              schema:
                type: string
              description: Suggested filename
          content:
            application/pdf:
              schema:
                type: string
                format: binary
            text/plain:
              schema:
                type: string
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'

  /api/jobs/{id}/apply:
    post:
      summary: Mark job as applied
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplyRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplyResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/jobs/{id}/notes:
    post:
      summary: Add a note to a job
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/jobs/{id}/interview:
    post:
      summary: Schedule an interview for a job
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InterviewRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterviewResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalError'

  /api/jobs/{id}/feedback:
    post:
      summary: Record company feedback for a job
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedbackRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedbackResponse'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Conflict:
      description: Conflict or precondition failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    UnprocessableEntity:
      description: Schema mismatch or invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    RateLimited:
      description: Rate limit exceeded
      headers:
        Retry-After:
          schema:
            type: integer
          description: Retry after milliseconds (optional)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object
              additionalProperties: true
          required: [code, message]
      required: [error]

    JobArtifactType:
      type: string
      enum: [cover-letter, cv]

    JobGenerationArtifact:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/JobArtifactType'
        contentType:
          type: string
        fileName:
          type: string
        createdAt:
          type: string
          format: date-time
      required: [type, contentType, fileName, createdAt]

    JobGenerationMetadata:
      type: object
      properties:
        runId:
          type: string
        generatedAt:
          type: string
          format: date-time
        types:
          type: array
          items:
            $ref: '#/components/schemas/JobArtifactType'
        artifacts:
          type: array
          items:
            $ref: '#/components/schemas/JobGenerationArtifact'
      required: [runId, generatedAt, types, artifacts]

    JobArtifactDocument:
      type: object
      properties:
        jobId:
          type: string
        runId:
          type: string
        type:
          $ref: '#/components/schemas/JobArtifactType'
        contentType:
          type: string
        fileName:
          type: string
        content:
          type: string
          description: Artifact content (encoded text or base64)
        createdAt:
          type: string
          format: date-time
      required: [jobId, runId, type, contentType, fileName, content, createdAt]

    ScrapedJob:
      type: object
      properties:
        id: { type: string }
        trackingId: { type: string }
        refId: { type: string }
        link: { type: string, format: uri }
        title: { type: string }
        companyName: { type: string }
        companyLinkedinUrl: { type: string }
        companyLogo: { type: string }
        companyEmployeesCount: { type: integer, nullable: true }
        location: { type: string }
        postedAt: { type: string, format: date-time }
        salaryInfo:
          type: array
          items: { type: string }
        salary: { type: string }
        benefits:
          type: array
          items: { type: string }
        descriptionHtml: { type: string }
        applicantsCount:
          oneOf:
            - { type: number }
            - { type: string }
        applyUrl: { type: string, format: uri }
        descriptionText: { type: string }
        seniorityLevel: { type: string, nullable: true }
        employmentType: { type: string }
        jobFunction: { type: string, nullable: true }
        industries: { type: string, nullable: true }
        inputUrl: { type: string, format: uri }
        companyAddress:
          type: object
          description: PostalAddress (opaque)
          additionalProperties: true
          nullable: true
        companyWebsite: { type: string, format: uri, nullable: true }
        companySlogan: { type: string, nullable: true }
        companyDescription: { type: string, nullable: true }
      required:
        - id
        - trackingId
        - refId
        - link
        - title
        - companyName
        - companyLinkedinUrl
        - companyLogo
        - location
        - postedAt
        - salaryInfo
        - salary
        - benefits
        - descriptionHtml
        - applicantsCount
        - applyUrl
        - descriptionText
        - employmentType
        - inputUrl

    Job:
      allOf:
        - $ref: '#/components/schemas/ScrapedJob'
        - type: object
          properties:
            filteredAt: { type: string, format: date-time }
            filterResult:
              oneOf:
                - { type: boolean }
                - type: object
                  properties:
                    error: { type: string }
                  required: [error]
            filteredBy: { type: string, description: MongoDB ObjectId as string }
            generation:
              $ref: '#/components/schemas/JobGenerationMetadata'
            appliedAt: { type: string, format: date-time, nullable: true }
          required: [filteredAt, filterResult, filteredBy]

    FilterRequest:
      type: object
      properties:
        promptId: { type: string }
        actorName: { type: string }
      required: [promptId, actorName]

    FilterAgentResult:
      type: object
      properties:
        jobs:
          type: array
          items: { $ref: '#/components/schemas/Job' }
        rejects:
          type: array
          items: { $ref: '#/components/schemas/Job' }
        errors:
          type: array
          items: { $ref: '#/components/schemas/Job' }
      required: [jobs, rejects, errors]

    GenerateRequest:
      type: object
      properties:
        types:
          type: array
          items:
            $ref: '#/components/schemas/JobArtifactType'

    GenerateAcceptedResponse:
      type: object
      properties:
        runId: { type: string }
        artifacts:
          type: array
          items:
            type: object
            properties:
              type: { $ref: '#/components/schemas/JobArtifactType' }
              url: { type: string, format: uri }
            required: [type, url]
      required: [runId, artifacts]

    ApplyRequest:
      type: object
      properties:
        appliedAt: { type: string, format: date-time }

    ApplyResponse:
      type: object
      properties:
        appliedAt: { type: string, format: date-time }
      required: [appliedAt]

    NoteRequest:
      type: object
      properties:
        text: { type: string }
        clientId: { type: string }
      required: [text]

    NoteResponse:
      type: object
      properties:
        id: { type: string }
        text: { type: string }
        createdAt: { type: string, format: date-time }
      required: [id, text, createdAt]

    InterviewRequest:
      type: object
      properties:
        scheduledAt: { type: string, format: date-time }
        timezone: { type: string }
        medium:
          type: string
          enum: [phone, video, onsite]
      required: [scheduledAt]

    InterviewResponse:
      type: object
      properties:
        scheduledAt: { type: string, format: date-time }
        timezone: { type: string }
        medium:
          type: string
          enum: [phone, video, onsite]
      required: [scheduledAt]

    FeedbackRequest:
      type: object
      properties:
        rating:
          type: string
          enum: [positive, neutral, negative]
        notes: { type: string }
        receivedAt: { type: string, format: date-time }

    FeedbackResponse:
      type: object
      properties:
        id: { type: string }
        rating:
          type: string
          enum: [positive, neutral, negative]
        notes: { type: string }
        receivedAt: { type: string, format: date-time }
      required: [id, receivedAt]

    IngestRequest:
      type: object
      properties:
        source: { type: string }
        limit: { type: integer }

    IngestSummary:
      type: object
      properties:
        added: { type: integer }
        skipped: { type: integer }
        failed: { type: integer }
        errors:
          type: array
          items:
            type: object
            properties:
              id: { type: string }
              message: { type: string }
            required: [message]
      required: [added, skipped, failed]
