import z from "zod";

export const ZJob = z.object({
    id: z.string(),
    trackingId: z.string(),
    refId: z.string(),
    link: z.string(),
    title: z.string(),
    companyName: z.string(),
    companyLinkedinUrl: z.string(),
    companyLogo: z.string(),
    companyEmployeesCount: z.optional(z.number()),
    location: z.string(),
    postedAt: z.date(),
    salaryInfo: z.array(z.string()),
    salary: z.string(),
    benefits: z.array(z.string()),
    descriptionHtml: z.string(),
    applicantsCount: z.union([z.number(), z.string()]),
    applyUrl: z.string(),
    descriptionText: z.string(),
    seniorityLevel: z.optional(z.string()),
    employmentType: z.string(),
    jobFunction: z.optional(z.string()),
    industries: z.optional(z.string()),
    inputUrl: z.string(),
    companyAddress: z.optional(z.object({
        type: z.string().optional().nullable(),
        streetAddress: z.string().optional().nullable(),
        addressLocality: z.string().optional().nullable(),
        addressRegion: z.string().optional().nullable(),
        postalCode: z.string().optional().nullable(),
        addressCountry: z.string().optional().nullable(),
    })),
    companyWebsite: z.optional(z.string()),
    companySlogan: z.optional(z.string()).nullable(),
    companyDescription: z.optional(z.string())
});